version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the app
          command: npm run build
workflows:          
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Install latest react-scripts
          command: npm install react

      - run:
          name: Update npm packages
          command: npm update

      - run:
          name: Build the app
          command: npm run build

      - run:
          name: Deploy to main server
          command: |
            sudo apt-get install -y sshpass
            sshpass -p $PASSWORD scp -r ./build/* $USERNAME@$HOSTNAME:/var/www/html/admin
