version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the app
          command: npm run build

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install dependencies
          command: |
            rm -rf node_modules
            npm install
      - run:
          name: Clear cache
          command: npm cache clean --force
      - run:
          name: Install latest react-scripts
          command: npm install react-scripts@latest
      - run:
          name: Update npm packages
          command: npm update
      - run:
          name: Build the app
          command: npm run build
      - run:
          name: Fix react-apexcharts module issue
          command: npm install apexcharts@latest
      - run:
          name: Deploy to main server
          command: |
            sudo apt-get install -y sshpass
            sshpass -p $PASSWORD scp -r ./build/* $USERNAME@$HOSTNAME:/var/www/html/admin

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
