name: Deploycode

on:
  push:
    branches:
     - main

jobs:
 
  build-and-deploy-live:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies test
      run: npm install
      
    - name:  latest react
      run : npm install react-scripts@latest
    - name: npm update
      run : npm update

    - name: Build the app
      run: npm run build:prod
      #hello
    - name: Deploy to main server
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        pass: ${{ secrets.PASSWORD }}
        user: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOSTNAME }}
        scp: |
          './build/*' => /var/www/
